// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ostwest_Shop.Server.DbContext;

#nullable disable

namespace Ostwest_Shop.Server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250104175413_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ostwest_Shop.Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Category_name");

                    b.HasKey("Id")
                        .HasName("Category_pk");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.Magazine", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.Property<int>("Quanity")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("Magazine_pk");

                    b.ToTable("Magazine", (string)null);
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgSourcePath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("img_source_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("Product_pk");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("User_pk");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.UserDatum", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("Birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("User_data_pk");

                    b.ToTable("User_data", (string)null);
                });

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.HasKey("CategoryId", "ProductId")
                        .HasName("Product_category_pk");

                    b.HasIndex("ProductId");

                    b.ToTable("Product_category", (string)null);
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.Magazine", b =>
                {
                    b.HasOne("Ostwest_Shop.Server.Models.Product", "Product")
                        .WithOne("Magazine")
                        .HasForeignKey("Ostwest_Shop.Server.Models.Magazine", "ProductId")
                        .IsRequired()
                        .HasConstraintName("Magazyn_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.UserDatum", b =>
                {
                    b.HasOne("Ostwest_Shop.Server.Models.User", "User")
                        .WithOne("UserDatum")
                        .HasForeignKey("Ostwest_Shop.Server.Models.UserDatum", "UserId")
                        .IsRequired()
                        .HasConstraintName("User_data_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.HasOne("Ostwest_Shop.Server.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Product_category_Category");

                    b.HasOne("Ostwest_Shop.Server.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Product_category_Product");
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.Product", b =>
                {
                    b.Navigation("Magazine");
                });

            modelBuilder.Entity("Ostwest_Shop.Server.Models.User", b =>
                {
                    b.Navigation("UserDatum");
                });
#pragma warning restore 612, 618
        }
    }
}
